title: Digital Music Edition
description: Maintained by The Virtual Research Group Edirom (ViFE) 
theme: jekyll-theme-cayman

collections:
  edirom-objects:
    output: true
    permalink: /:collection/:name